# updateCapacity.py
# updatePledges.py
python updateDiskServersInIntervention.py
python updateDowntimes.py
python updateGgusTickets.py
python updateNotices.py
python updateStorageUsageDataSource_VO.py
python updateStorageUsageDataSource_MoreDetails.py
python updateGanglia.py
