# updateCapacity.py
# updatePledges.py
python2.7 updateDiskServersInIntervention.py
python2.7 updateDowntimes.py
python2.7 updateGgusTickets.py
python2.7 updateNotices.py
python2.7 updateStorageUsageDataSource_VO.py
python2.7 updateStorageUsageDataSource_MoreDetails.py
python2.7 updateGanglia.py
